name: Called Maven Workflow
 
on:
  workflow_call:
    inputs:
      mavenPomFile:
        required: true
        type: string
      options:
        required: false
        type: string
      testRunTitle:
        required: false
        type: string
 
jobs:
  maven-build:
    runs-on: windows-latest
 
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      # Set up Java (required for Maven)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
 
      # Run Maven commands using PowerShell
      - name: Run Maven Build
        shell: pwsh
        run: |
          Write-Host "Starting Maven Build Process"
          Write-Host "Using POM File: ${{ inputs.mavenPomFile }}"
          Write-Host "Options: ${{ inputs.options }}"
          Write-Host "Test Run Title: ${{ inputs.testRunTitle }}"
          # Navigate to the directory containing the POM file
          cd $(Split-Path -Path "${{ inputs.mavenPomFile }}")
 
          # Run Maven command
          mvn clean install ${{ inputs.options }}
