name: Main Workflow.

on:
  push:
    branches:
      - main
      - feature
  workflow_dispatch:

jobs:
  call-maven-workflow:
    uses: ./.github/workflows/template_maven.yml
    with:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: 'false'
      testRunTitle: 'Write title here'
      jdkVersionOption: '8'
      mavenOptions: '-B -X'
